server:
  port: ${port:2267}
#  instance:
#    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka:
  client:
    enabled: false

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000
 
hystrix:
  command:
    getRandom:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

management:
  security:
    enabled: false
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: '*'

spring:
  cloud:
    consul:
      enabled: true
      host: 172.16.16.16
      port: 8500
      discovery:
        healthCheckUrl: http://localhost:${server.port}/manage/health
        healthCheckInterval: 20s
  rabbitmq:
    host: ${mqhost:rabbitmqhost}
    port: ${mqport:5672}
    username: ${mquser:guest}
    password: ${mquser:guest}

hello:
  world: Hello World 667