server:
  port: ${port:2268}
      
#  instance:
#    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /manage/health
        healthCheckInterval: 20s
  rabbitmq:
    host: ${mqhost:rabbitmqhost}
    port: ${mqport:5672}
    username: ${mquser:guest}
    password: ${mquser:guest}

management:
  security:
    enabled: false
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: '*'

test:
  value: PROPVALUE-67        
  