server:
  port: ${port:2268}
      
#  instance:
#    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  security:
    enabled: false
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: '*'

spring:
#  rabbitmq:
#    host: ${mqhost:rabbitmqhost}
#    port: ${mqport:5672}
#    username: ${mquser:guest}
#    password: ${mquser:guest}
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
            
test:
  value: PROPVALUE-67        
  