server:
  port: ${port:2268}
#  instance:
#    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${registry.url:http://localhost:8761/eureka/}

management:
  security:
    enabled: false
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: '*'
        
spring:
  cloud:
    consul:
      enabled: false
  rabbitmq:
    host: ${mqhost:rabbitmqhost}
    port: ${mqport:5672}
    username: ${mquser:guest}
    password: ${mquser:guest}
            
test:
  value: PROPVALUE-667