server:
  port: ${zuul.port:7777}

eureka:
  client:
    enabled: false 

zuul:
  routes:
    microservices-1:
      path: /rb/** #optional - this is here for illustration only that microservice-1 can also be accessed using URI /rb

management:
  security:
    enabled: false
  endpoints:
    web:
      basePath: /manage
      exposure:
        include: '*'

spring:
  cloud:
    consul:
      enabled: true
      host: ${consulhost:localhost}
      port: 8500
      discovery:
        healthCheckUrl: http://localhost:${server.port}/manage/health
        healthCheckInterval: 20s
  rabbitmq:
    host: ${mqhost:rabbitmqhost}
    port: ${mqport:5672}
    username: ${mquser:guest}
    password: ${mquser:guest}
    
ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000